language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-license-bcbbd656
    - android-sdk-license-5be876d5
    - '.*intel.+'

#notifications:
#  email: false

before_install:
  # Fix Gradle output
  - export TERM=dumb

script:
  - ./gradlew check
